import { ImovelGalleriesType } from "@/types/galerias";


export const newgalerias: ImovelGalleriesType = {
  id: 1,
  galleries: [
    {
      name: "Galeria 1",
      images: [
        {
          id: "1",
          alt: "Imagem 1",
          src: "https://picsum.photos/200",
          thumbnail: "https://picsum.photos/200",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "2",
          alt: "Imagem 2",
          src: "https://picsum.photos/201",
          thumbnail: "https://picsum.photos/201",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "3",
          alt: "Imagem 3",
          src: "https://picsum.photos/202",
          thumbnail: "https://picsum.photos/202",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "4",
          alt: "Imagem 4",
          src: "https://picsum.photos/203",
          thumbnail: "https://picsum.photos/203",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "5",
          alt: "Imagem 5",
          src: "https://picsum.photos/204",
          thumbnail: "https://picsum.photos/204",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "6",
          alt: "Imagem 6",
          src: "https://picsum.photos/205",
          thumbnail: "https://picsum.photos/205",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
      ],
      currentImage: {
        id: "4",
        alt: "Imagem 4",
        src: "https://picsum.photos/203",
        thumbnail: "https://picsum.photos/203",
        caption: "Descrição da Imagem 1",
        type: "img",
        onclick: () => console.log(self),
      },
    },
    {
      name: "Galeria 2",
      images: [
        {
          id: "7",
          alt: "Imagem 1",
          src: "https://picsum.photos/200",
          thumbnail: "https://picsum.photos/200",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "8",
          alt: "Imagem 2",
          src: "https://picsum.photos/201",
          thumbnail: "https://picsum.photos/201",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "9",
          alt: "Imagem 3",
          src: "https://picsum.photos/202",
          thumbnail: "https://picsum.photos/202",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "10",
          alt: "Imagem 4",
          src: "https://picsum.photos/203",
          thumbnail: "https://picsum.photos/203",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "11",
          alt: "Imagem 5",
          src: "https://picsum.photos/204",
          thumbnail: "https://picsum.photos/204",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "12",
          alt: "Imagem 6",
          src: "https://picsum.photos/205",
          thumbnail: "https://picsum.photos/205",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "13",
          alt: "Imagem 1",
          src: "https://picsum.photos/200",
          thumbnail: "https://picsum.photos/200",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "14",
          alt: "Imagem 2",
          src: "https://picsum.photos/201",
          thumbnail: "https://picsum.photos/201",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "15",
          alt: "Imagem 3",
          src: "https://picsum.photos/202",
          thumbnail: "https://picsum.photos/202",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "16",
          alt: "Imagem 4",
          src: "https://picsum.photos/203",
          thumbnail: "https://picsum.photos/203",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "17",
          alt: "Imagem 5",
          src: "https://picsum.photos/204",
          thumbnail: "https://picsum.photos/204",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "18",
          alt: "Imagem 6",
          src: "https://picsum.photos/205",
          thumbnail: "https://picsum.photos/205",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
      ],
      currentImage: {
        id: "15",
        alt: "Imagem 3",
        src: "https://picsum.photos/202",
        thumbnail: "https://picsum.photos/202",
        caption: "Descrição da Imagem 3",
        type: "img",
        onclick: () => console.log(self),
      },
    },
    {
      name: "Galeria 3",
      images: [
        {
          id: "1",
          alt: "Imagem 1",
          src: "https://picsum.photos/200",
          thumbnail: "https://picsum.photos/200",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "2",
          alt: "Imagem 2",
          src: "https://picsum.photos/201",
          thumbnail: "https://picsum.photos/201",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "3",
          alt: "Imagem 3",
          src: "https://picsum.photos/202",
          thumbnail: "https://picsum.photos/202",
          caption: "Descrição da Imagem 3",
          type: "iframe",
          onclick: () => console.log(self),
        },
        {
          id: "4",
          alt: "Imagem 4",
          src: "https://picsum.photos/203",
          thumbnail: "https://picsum.photos/203",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "5",
          alt: "Imagem 5",
          src: "https://picsum.photos/204",
          thumbnail: "https://picsum.photos/204",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "6",
          alt: "Imagem 6",
          src: "https://picsum.photos/205",
          thumbnail: "https://picsum.photos/205",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
      ],
      currentImage: {
        id: "4",
        alt: "Imagem 4",
        src: "https://picsum.photos/203",
        thumbnail: "https://picsum.photos/203",
        caption: "Descrição da Imagem 1",
        type: "img",
        onclick: () => console.log(self),
      },
    },
    {
      name: "Galeria 4",
      images: [
        {
          id: "7",
          alt: "Imagem 1",
          src: "https://picsum.photos/200",
          thumbnail: "https://picsum.photos/200",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "8",
          alt: "Imagem 2",
          src: "https://picsum.photos/201",
          thumbnail: "https://picsum.photos/201",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "9",
          alt: "Imagem 3",
          src: "https://picsum.photos/202",
          thumbnail: "https://picsum.photos/202",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "10",
          alt: "Imagem 4",
          src: "https://picsum.photos/203",
          thumbnail: "https://picsum.photos/203",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "11",
          alt: "Imagem 5",
          src: "https://picsum.photos/204",
          thumbnail: "https://picsum.photos/204",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "12",
          alt: "Imagem 6",
          src: "https://picsum.photos/205",
          thumbnail: "https://picsum.photos/205",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "13",
          alt: "Imagem 1",
          src: "https://picsum.photos/200",
          thumbnail: "https://picsum.photos/200",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "14",
          alt: "Imagem 2",
          src: "https://picsum.photos/201",
          thumbnail: "https://picsum.photos/201",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "15",
          alt: "Imagem 3",
          src: "https://picsum.photos/202",
          thumbnail: "https://picsum.photos/202",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "16",
          alt: "Imagem 4",
          src: "https://picsum.photos/203",
          thumbnail: "https://picsum.photos/203",
          caption: "Descrição da Imagem 1",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "17",
          alt: "Imagem 5",
          src: "https://picsum.photos/204",
          thumbnail: "https://picsum.photos/204",
          caption: "Descrição da Imagem 2",
          type: "img",
          onclick: () => console.log(self),
        },
        {
          id: "18",
          alt: "Imagem 6",
          src: "https://picsum.photos/205",
          thumbnail: "https://picsum.photos/205",
          caption: "Descrição da Imagem 3",
          type: "img",
          onclick: () => console.log(self),
        },
      ],
      currentImage: {
        id: "15",
        alt: "Imagem 3",
        src: "https://picsum.photos/202",
        thumbnail: "https://picsum.photos/202",
        caption: "Descrição da Imagem 3",
        type: "img",
        onclick: () => console.log(self),
      },
    },
  ],
};
