import { SimpleMessage } from "@/components/layout/messages/SimpleMessage";
import { FooterPage } from "@/components/layout/navigations/FooterPage";
import { HeaderPage } from "@/components/layout/navigations/HeaderPage";
import { Menu } from "@/components/layout/navigations/Menu";
import { Providers } from "@/lib/provider-query";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="border-b-1 border-secondary">
            <SimpleMessage
              message={"Mensagens promocionais para os clientes"}
            />
            <HeaderPage />
            <Menu />
          </header>

          {children}

          <footer>
            <FooterPage />
          </footer>
        </body>
      </html>
    </Providers>
  );
}
